### ISSUE TITLE
Active Comments Processes

### ISSUE THREAD

**Issue by Ecstasyyy1337** [HerrEurobeat/steam-comment-service-bot#103]
I think it would be useful to add !sessions to see all active commenting sessions
Respond > : .STEAMID64. sent/total

!mysessions to see only my active commenting sessions
Respond > : .STEAMID64. sent/total

Also to abort one specific session use !kill .STEAMID64.

add a switcher to true / false in the advanced config, btw this is useful for proxy users

**Comment by HerrEurobeat** [comment]
I added both commands as shown in the referenced commit above.  
The !sessions command is owner only and the !mysessions command can be used by anyone.  

To "kill" a session you can use the already existing command `!abort (reciever id)`.
