### ISSUE TITLE
Retry fails & New fails script

### ISSUE THREAD

**Issue by Ecstasyyy1337** [HerrEurobeat/steam-comment-service-bot#104]
I sugggest a new option that can be switched in the advancedconfig.json for all the fails that commentbot gets to retry them and tell you its finished only after all comments were sent. Also make a new system for the fails since if you start more processes same time the fails are bugged and it tell you all fails in that period, not only for the commented ID.

**Comment by HerrEurobeat** [comment]
I will take a look at how I can improve the bot usage for multiple big comment requests in 2.12.

**Comment by HerrEurobeat** [comment]
Retrying comments has been implemented in version 2.12 and is now available on the master branch!
