### ISSUE TITLE
Waiting for websession....

### ISSUE THREAD

**Issue by addee99** [HerrEurobeat/steam-comment-service-bot#107]
[2021-07-09 03:27:45] [Bot 2] Account logged in! Waiting for websession...

It's stuck there. Nothing more. What to do? 

edit: Fixed it!

**Comment by HerrEurobeat** [comment]
Good to hear you resolved the issue.  
I'm going to close this issue but if you are encountering the same issue again feel free to reopen!  
If you are having another issue feel free to open another issue.  
Thanks!
