### ISSUE TITLE
Max comment

### ISSUE THREAD

**Issue by addee99** [HerrEurobeat/steam-comment-service-bot#108]
Where in the code can I change so max comments is not just 1? I would like to mass comment with 100 accounts.

**Comment by Ecstasyyy1337** [comment]
go into `config.json` and modify     `maxComments`  if you want maxComments for all bot users or modify  `maxOwnerComments` for owners only

**Comment by HerrEurobeat** [comment]
Yup, exactly what @Ecstasyyy1337 said. Thanks for answering the issue :)

**Comment by addee99** [comment]
I've set maxcomment to 100. But when I i write " !comment 3 " to the bot, I get this "You can request max. 1 comments.
Command usage: '!comment number_of_comments/"all" profileid' for X many or the max amount of comments (max 1). Provide a profile id to comment on a specific profile."

**Comment by HerrEurobeat** [comment]
Can you please take a look at the log? Does it maybe say:  
`config.json seems to have lost it's data/is corrupted. Trying to restore from backup...`  
somewhere?  

If yes, then you probably made a Syntax mistake. Check if you correctly changed the number without for example removing the comma at the end of the line.

**Comment by addee99** [comment]
https://gyazo.com/ac4637a1e70ad59c5a824c68d46fba02 Should be right?
Where do I find the log?

**Comment by HerrEurobeat** [comment]
If you set yourself as owner and then set `maxOwnerComments` to 0 then you will be able to only request 1 comment.  
Increase `maxOwnerComments` to 100 aswell and you will be able to request 100 comments.  

Don't forget to increase your commentdelay to not get a cooldown nearly instantly from Steam. (I also hope you are using more than 1 account)

**Comment by addee99** [comment]
Great! Worked. I have another question. Since I have steamguard on mail, Do I always need to put in the code when trying to login... Or will the bot "remember" the accounts?

**Comment by HerrEurobeat** [comment]
The bot will remember E-Mail Steam Guard accounts. Mobile Steam Guard accounts need their code to be typed in every time (just like when logging in on the website) except if you provide a shared_secret.

**Comment by addee99** [comment]
Great! Thanks for the help
