### ISSUE TITLE
Can only do 13 comments

### ISSUE THREAD

**Issue by addee99** [HerrEurobeat/steam-comment-service-bot#109]
I have 20 accounts, but when I try !comment 20 I don't get 20 comments. Even if I have waited 15 hours before doing it. I get like 13 comments only. Here's my settings https://gyazo.com/4b289131cd6b63ac6e429bad000cd3a0
and here is what it says in the cmd "https://gyazo.com/874886ea79ee39f19acaaefe024367d0"

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue and sorry for the late reply.  
Your mistake is that you set a wayyy too low commentdelay and Steam applies a cooldown to your IP as you can see in your second screenshot (HTTP 429 is an IP cooldown error which is used nearly everywhere on the internet to limit the amount of requests an IP can do to avoid spam and reduce load).  

Please set your commentdelay to 7500 or something like that and test again. The default value is 15000 ms.  
The more comments you want to request the higher you will probably need to set your delay. Depending on how many accounts you use you might want to think about using proxies.
