### ISSUE TITLE
 Error while processing comment request: Error: id parameter should be a user URL string or a SteamID object

### ISSUE THREAD

**Issue by FishyFishsEatingFishs** [HerrEurobeat/steam-comment-service-bot#116]
Error while processing comment request: Error: id parameter should be a user URL string or a SteamID object

![image](https://user-images.githubusercontent.com/87787187/136795863-03c5f4d3-b360-4a0b-b2ae-54bbba1f00d6.png)

**Comment by HerrEurobeat** [comment]
This should not be able to happen anymore on version 2.12 so I'm closing this one.
