### ISSUE TITLE
apm audit and npm fund fix

### ISSUE THREAD

**Issue by alexandrubo** [HerrEurobeat/steam-comment-service-bot#121]
**Error/Element that doesn't work**
Hello,i run npm install and i get errors from screenshot,can someone help me pls?
I can give TeamViewer for help,add me on discord Al3xandru.#3080

**Additional information**
I run commands for auto-fix.
![errori de kkt](https://user-images.githubusercontent.com/34989571/147851729-a01b67fd-541d-44a6-8e01-2b1dc74c09b6.png)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
You don't need to run any audit or fix command. Just run `npm install` and the packages will be installed (which worked without any errors in your screenshot).  
NPM is just letting you know that there are updates available for some packages that fix some security vulnerability. You can ignore that message.  

I'm going to update all dependencies which might make the warning go away, however if the mentioned package is used by another package then I have to wait for the other package maintainer to update their dependencies first.  
  
  
TL;DR: Just run `npm install` and ignore the warning, you don't need to do anything.

**Comment by HerrEurobeat** [comment]
I'm not able to resolve the warning as the outdated package (which generates the warning) is a dependency from another package.  
Not a big deal, as I said, you can just ignore the warning.

**Comment by alexandrubo** [comment]
ok bro,thx so much <3

**Comment by HerrEurobeat** [comment]
No problem

**Comment by HerrEurobeat** [comment]
Reworded title and pinned issue so others with the same question will see my response

**Comment by HerrEurobeat** [comment]
The bot now handles installing and updating NPM packages itself so this message should be visible anymore.  
I'm therefore unpinning the issue.
