### ISSUE TITLE
auto-accept problem

### ISSUE THREAD

**Issue by tailon222** [HerrEurobeat/steam-comment-service-bot#124]
Hi, i have a question, is there any way to stop accepting friend request from random people? i would like that the bot only auto-accept the owner.

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
This is a planned feature that will be coming in version 2.12.  
I can't guarantee when the update will come though as I'm quite busy atm but I'll give my best.

**Comment by tailon222** [comment]
Okay thanks for the info, take your time there's no rush! i can just put the command "!comment" for only owner as temporary fix.
Btw i had another problem with the option "unfriendtime", when i set it to 0, it doesnt actually disable it still unfriends people so my solution was put alot of days. That happend to me when i first start the bot, so is not like has past 1 day since the last comment. (i don't know how it works and i have not idea how to code). I had the idea that the code checks if the guy has been offline less than 1 day then the bot will removed him, but now that i have read the wiki it doesn't work like that so i don't know what could happend there.

**Comment by HerrEurobeat** [comment]
Huh interesting, thanks for letting me know!  
I'll make a note and look into it.  
  
How it should work:  
Every time someone requests comments or adds the bot as friend it makes an entry in a database with a timestamp.  
It then checks the whole database every 60 seconds for timestamps that are less than the current timestamp minus unfriendtime.  
If it finds someone (who is not an owner) it will unfriend them with all bot accounts and delete them from the database.

**Comment by tailon222** [comment]
Thanks for the info of how it works and thanks for fixing it!
