### ISSUE TITLE
Error: Cannot find module './logininfo.json'

### ISSUE THREAD

**Issue by Kamel002** [HerrEurobeat/steam-comment-service-bot#13]
PS C:\Users\Alex\Desktop\profilcomentgo\steam-comment-service-bot-master> node start.js
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module './logininfo.json'
Require stack:
- C:\Users\Alex\Desktop\profilcomentgo\steam-comment-service-bot-master\start.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:862:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1042:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (C:\Users\Alex\Desktop\profilcomentgo\steam-comment-service-bot-master\start.js:6:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:1156:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:899:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\Alex\\Desktop\\profilcomentgo\\steam-comment-service-bot-master\\start.js'[39m
  ]
}
PS C:\Users\Alex\Desktop\profilcomentgo\steam-comment-service-bot-master>

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.
Did you rename `logininfo.json.example` to `logininfo.json?`

I am planning on removing that rename process in the next update to make it easier to setup the bot for the first time.

**Comment by HerrEurobeat** [comment]
Since you didn't reply I assume you found the wrong password and it is working now.
If this problem is still present, feel free to just comment again.
If you encounter another problem/error/bug, please open another issue.
Thanks!
