### ISSUE TITLE
comment 0

### ISSUE THREAD

**Issue by Stiefel1234eu** [HerrEurobeat/steam-comment-service-bot#131]
**Describe the bug**
If you send the bot `!comment 0 *steamid*` the bot will be in a loop..
Therefore u cannot request a new comment:
`This profile is currently recieving previously requested comments. Please wait for them to be completed.`

![image](https://user-images.githubusercontent.com/63855548/175823361-e8ed3193-9a49-4339-8c62-0cedbdd6476e.png)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue and sorry for the late response - I was on vacation.  
I can indeed confirm the issue on the latest master version `2.11.1` however it seems to be fixed already in the latest beta version `BETA 2.12 b8`.  
  
I'm going to leave this issue open until `2.12` is out on the master branch. I don't think a hotfix for `2.11` is necessary.  
  
Thanks for reporting!

**Comment by HerrEurobeat** [comment]
Version 2.12 is now out so I'm closing this one.
