### ISSUE TITLE
[Question] Regarding IP bans quoted by you.

### ISSUE THREAD

**Issue by X8J** [HerrEurobeat/steam-comment-service-bot#134]
'It drastically reduces the amount of requests on one IP by equally spreading all accounts onto different IPs, allowing you to comment more and faster, reducing the chance of an IP ban.' - Said by you in the wiki of adding proxies.
Does steam actually IP ban for this type of stuff? Never ever heard of it. I know they used to IP ban back in LAN days but rarely anymore.
Do you mean ratelimit your IP or something?
Thanks

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
Yes, you are right, by (temporary) IP banning I mean ratelimiting (HTTP Error 429).  
I just tried to describe it with more simple terms and differentiate between account and IP cooldowns.

**Comment by HerrEurobeat** [comment]
Since you didn't reply I am going to close this issue and hope that I answered your question.
If not, feel free to reopen this issue or please create another issue if there is something else on your mind!

**Comment by X8J** [comment]
Ah ok, didnt see you responded but yes you answered my question
