### ISSUE TITLE
Steam id error

### ISSUE THREAD

**Issue by yungheheh** [HerrEurobeat/steam-comment-service-bot#135]
![obraz_2022-09-02_190843986](https://user-images.githubusercontent.com/112720658/188204107-c403311b-27a6-4620-b42d-60a537b4f99f.png)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue and thanks for reporting this error!  
This looks like an oversight in my code, so I'm going to change the label from question to bug.  
For now you can ignore this error, it shouldn't impact anything.  
  
I'm going to leave this issue open until the bug is fixed

**Comment by yungheheh** [comment]
will I get my items in my inventory?

pt., 2 wrz 2022 o 23:52 3urobeat ***@***.***> napisał(a):

**Comment by HerrEurobeat** [comment]
What do you mean? The bot does not interact with any inventory.

**Comment by XdekHckr** [comment]
> will I get my items in my inventory? 

Ten program służy do komentowania profili, nie ma związku z żadnymi przedmiotami w ekwipunku

**Comment by yungheheh** [comment]
Nvm

niedz., 4 wrz 2022, 07:41 użytkownik XdekHckr ***@***.***>
napisał:

**Comment by yungheheh** [comment]
I didnt get my items from promo case. Can I get them?

sob., 3 wrz 2022 o 22:51 3urobeat ***@***.***> napisał(a):

**Comment by HerrEurobeat** [comment]
What are you talking about? I think you are a little confused, this repository is about my steam **comment** service bot, it has nothing to do with items, nor any "shady" promotions.

**Comment by HerrEurobeat** [comment]
This should fix this issue by making sure that steamID is populated before proceeding. I'll keep this issue open until version `2.12.1` is out on the master branch.

**Comment by HerrEurobeat** [comment]
Version 2.12.1 is now out on the master branch and fixes this issue.  
See the release notes [here](https://github.com/HerrEurobeat/steam-comment-service-bot/releases/tag/2.12.1).
