### ISSUE TITLE
"commentcooldown" bug

### ISSUE THREAD

**Issue by Stiefel1234eu** [HerrEurobeat/steam-comment-service-bot#14]
When unfriendtime = 0, the user cooldown doesn't work anymore

**Comment by HerrEurobeat** [comment]
I can recreate the issue on the latest master version 2.5.1 although not anymore in the beta 2.6 build 6 -  so I probably fixed it without knowing or it fixed itself. 
Waiting for version 2.6 master push before closing this issue.

**Comment by HerrEurobeat** [comment]
Nervermind, I could now recreate the issue and removed the if check that caused it.

**Comment by HerrEurobeat** [comment]
Fixed in master commit 0d0f633051.
