### ISSUE TITLE
WARN] [Main] Error: InvalidParam while trying to get a new session for '---' using login credentials. Retrying login in 5 seconds...

### ISSUE THREAD

**Issue by memendes123** [HerrEurobeat/steam-comment-service-bot#149]
**Error/Element that doesn't work**
[2023-03-02 21:44:57 | WARN] [Main] Error: InvalidParam while trying to get a new session for '---' using login credentials. Retrying login in 5 seconds...

**Additional information**
whenever I log in this error appears, I checked everything and I have all the right data, but I can't log in

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue! I'll comment in #148 as it is about the same topic \^\^
