### ISSUE TITLE
All comments have been sent. Failed: 0/X

### ISSUE THREAD

**Issue by Stiefel1234eu** [HerrEurobeat/steam-comment-service-bot#15]
The bot sends the following messages after !comment
Seems to be random how many you will get

All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5
All comments have been sent. Failed: 0/5

**Comment by HerrEurobeat** [comment]
Issue found and fixed in latest beta push, waiting for version 2.6 master push before closing this issue.

**Comment by HerrEurobeat** [comment]
Fixed in master commit 0d0f633051.
