### ISSUE TITLE
Artwork comments 

### ISSUE THREAD

**Issue by callmetekkezs** [HerrEurobeat/steam-comment-service-bot#156]
**Describe the solution you'd like**
A clear description of what should happen.

**Additional context**

**Comment by callmetekkezs** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2947062487

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
Artwork comments have been a common requested feature over the years. The `node-steamcommunity` library which I'm using to comment however does not support commenting on artworks afaik so I would need to figure out how to do this manually.  
It is relatively high on my priority list but I'm not sure if I'll come around to checking it out for the upcoming 2.13 release. We'll see.

**Comment by callmetekkezs** [comment]
oh ok ty

**Comment by HerrEurobeat** [comment]
Version 2.13 is out on master which adds support for this suggestion.  
Check out the release notes [here](https://github.com/HerrEurobeat/steam-comment-service-bot/releases/tag/2.13.0)!
