### ISSUE TITLE
Error with adding a bot in steam

### ISSUE THREAD

**Issue by AIexell** [HerrEurobeat/steam-comment-service-bot#157]
**Describe the bug**
I decided to start requesting comments, I got an error that I need to add the bot as a friend. By clicking on the link indicated in the message, I saw that the bot is in my friends. However, after a second request for cheating, I got a second message stating that supposedly I had not added it.

**Full error**
My message: "!comment 20"

Bot response: "Please add these accounts and then request again: (limited accounts)' http://steamcommunity.com/profiles/76561199251753174 '"
![Screenshot_1](https://user-images.githubusercontent.com/129078659/227967340-4edd2305-9fab-4990-9e69-280995c7ca51.png)

![Screenshot_2](https://user-images.githubusercontent.com/129078659/227968323-a07ca1ff-531c-437b-b37f-680905411f24.png)

**Additional context**
Because of this error, I can't get comments at all, because the error keeps popping up when re-typing the command.

**Comment by HerrEurobeat** [comment]
Thanks for opening an issue!  
This behavior seems to occur when not enough accounts could be found for the request due to them having lost connection previously.  
This should improve in version `2.13` when I'm finished reworking how bot accounts and their status are stored.

**Comment by HerrEurobeat** [comment]
Version 2.13 is out on master which likely fixes this issue.  
Check out the release notes [here](https://github.com/HerrEurobeat/steam-comment-service-bot/releases/tag/2.13.0)!  

I'm going to close this issue for now, please reopen if you should still encounter this problem. Thanks!
