### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by stephanschorer** [HerrEurobeat/steam-comment-service-bot#158]
I found a mistake in the **Integrating into your own application** documentation.
https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Integrating-into-your-own-application

You wrote:
> First make sure that enableurltocomment is set to true in your config.json. If that is the case and you start the bot then you should see a message like this:

but the "enableurltocomment" is located in the advancedconfig.json 😊

Cheers

**Comment by HerrEurobeat** [comment]
Oops!  
Thanks for noticing; I forgot to update that. There are probably a few more mistakes in the other pages as well.  
That page will change again for version 2.13 btw as I'm currently adding a proper plugin system.

**Comment by HerrEurobeat** [comment]
Page has been updated to reflect the changes made in version 2.13.  
In short: Enabling the webserver and getting its key is now done in the plugin config of the webserver plugin. You can find it in the `plugins/steam-comment-bot-webserver` folder after starting the bot on version 2.13 at least once.  
Thanks again for letting me know!
