### ISSUE TITLE
Rate up csgo screenshot 

### ISSUE THREAD

**Issue by PlueTah** [HerrEurobeat/steam-comment-service-bot#161]
**Describe the solution you'd like**
A clear description of what should happen.
Rate up csgo screenshot **Additional context**

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
Support for screenshot/artwork likes is already planned for version 2.13, no guarantee though.  
I haven't planned anything csgo related yet though.

**Comment by PlueTah** [comment]
does it work rateup

**Comment by PlueTah** [comment]
ty
