### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by Seyhnsah** [HerrEurobeat/steam-comment-service-bot#162]
**Error/Element that doesn't work**
Please include the full error you get or if you get none, describe precisely what happened.

**Additional information**
Please add any other information here if you have some.

This does not seem to be a valid steamID64, profile or group link or you provided the wrong steamID type for this command!
A profile steamID64 must look like this: 7656119824002346
...or a group steamID64 like this: 13582796535471227

I can't make group comments.... I wrote 6 accounts. 
how many accounts do i have to write?

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
It looks like that you are trying to comment in a group using the "normal" profile comment command.  
Try again using the command `!groupcomment`.  
I'll probably remove the command in version 2.13 and just detect group links with the normal comment command, for now however you still need to use the separate command.

**Comment by Seyhnsah** [comment]
ok thanks. 
and i need sharedfiles comment
my sharedfiles : https://steamcommunity.com/sharedfiles/filedetails/?id=2377261244

**Comment by HerrEurobeat** [comment]
Support for comments on artworks etc. is already planned for 2.13, no guarantee though
