### ISSUE TITLE
Artwork Screenshot comment + favorurite + ra te up (like)

### ISSUE THREAD

**Issue by haxozidirf** [HerrEurobeat/steam-comment-service-bot#166]
**Describe the solution you'd like**
A clear description of what should happen.

**Additional context**

**Comment by HerrEurobeat** [comment]
Thanks for opening an issue!  
These are already planned for v2.13, please see #156 and #161.  
Thanks again!

**Comment by BHEDijital** [comment]
y

**Comment by BHEDijital** [comment]
y

**Comment by HerrEurobeat** [comment]
Version 2.13 is out on master which adds support for this suggestion.  
Check out the release notes [here](https://github.com/HerrEurobeat/steam-comment-service-bot/releases/tag/2.13.0)!
