### ISSUE TITLE
comment request via enableurltocomment

### ISSUE THREAD

**Issue by stephanschorer** [HerrEurobeat/steam-comment-service-bot#172]
**Describe the bug**
node cannot find the comment.js file.
Probably because there is no comment.js anymore 😊:

- commentgroup.js
- commentmisc.js
- commentprofile.js

**Full error**

```
Error while processing comment request: Error: Cannot find module '../src/bot/commands/comment/comment.js'
Require stack:
- /home/steam_commentbot/plugins/webserver.js
- /home/steam_commentbot/src/controller/helpers/loadPlugins.js
- /home/steam_commentbot/src/controller/ready.js
- /home/steam_commentbot/src/controller/helpers/logger.js
- /home/steam_commentbot/src/starter.js
- /home/steam_commentbot/src/controller/controller.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at /home/steam_commentbot/plugins/webserver.js:96:21
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Additional context**
bot version: 2.12.5

Cheers
Stephan

**Comment by HerrEurobeat** [comment]
hahaha oh shit, you noticed  
But for real, that's actually funny. I found out round about a month ago that the webserver was broken for ages, had to laugh quite a bit and then thought "naahh, no one uses that anyway, I'm just going to fix that in 2.13 when I need to rework the webserver anyway and nobody will notice"  
Well, about that...  

How important is the webserver for you right now? Version 2.13 is nearly done (I guess it's ready in ~1 week).  
Nearly everything has been reworked and it has a proper plugin support now, including a working webserver (wow!).  
If that would be okay I'd rather not fix that in 2.12.5 now and just ship 2.13 with a working one.  

Sorry for the inconvenience and thanks for reporting any bugs as always :D

**Comment by stephanschorer** [comment]
na its fine... keep your time

**Comment by BHEDijital** [comment]
what's new in 2, 13 ?

**Comment by HerrEurobeat** [comment]
I will write detailed patchnotes when the update is ready but the main features are:  
New plugin system, complete rework of the code structure (this was necessary for proper plugin support), support for commenting, voting & favoriting sharedfiles (screenshots, artworks & guides), cutting chat messages intelligently and handling failed chat messages better.   
I'll post a link to the complete patchnotes here when I have written them.

**Comment by HerrEurobeat** [comment]
Version 2.13 is out on master which fixes this issue.  
Check out the release notes [here](https://github.com/HerrEurobeat/steam-comment-service-bot/releases/tag/2.13.0)!
