### ISSUE TITLE
BUG ? ERROR https://prnt.sc/yo_HCm0u4wlj

### ISSUE THREAD

**Issue by PlueTah** [HerrEurobeat/steam-comment-service-bot#175]
**Describe the bug**
A clear description of what you did and what happened.

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

**Comment by PlueTah** [comment]
It gives an error even though the account information is correct

**Comment by PlueTah** [comment]
thanks

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
Idk what's going on there, I will need to check it out further. If you could post more content from your `output.txt` from above and below the error that would be helpful.

**Comment by PlueTah** [comment]
btw does rateup work?

**Comment by PlueTah** [comment]
> Hey, thanks for opening an issue.
> Idk what's going on there, I will need to check it out further. If you could post more content from your `output.txt` from above and below the error that would be helpful.

ok

**Comment by HerrEurobeat** [comment]
> btw does rateup work?

Yes but you need unlimited accounts

**Comment by PlueTah** [comment]
[](url)https://dosya.co/h4knmsb4t6oe/output.txt.html

**Comment by HerrEurobeat** [comment]
The status update error is fixed. You can either wait for the next version or force an update now by running `!update true`.  
I was unable to replicate the InvalidPassword issue you mentioned, it works as expected for me. Are you sure you haven't made a mistake in your `accounts.txt` file?

**Comment by HerrEurobeat** [comment]
Thanks for the donation @PlueTah! I appreciate it a lot :)
