### ISSUE TITLE
I have 35 accounts, what can I do with these accounts?

### ISSUE THREAD

**Issue by Maniifest** [HerrEurobeat/steam-comment-service-bot#178]
**Question or issue you are experiencing**
Please explain your question here. If you've got an error or something else related, then please include it here as well.

**Additional information**
Please add any other information here if you have some.

**Comment by HerrEurobeat** [comment]
Hey!  
If the accounts are limited (aka they have spent less than 5 dollars on the Steam Store) you can do this:  
- Comment on profiles of friends
- Comment on sharedfiles (aka screenshots, artworks & guides)
- Favorize sharedfiles

If the accounts are unlimited, you can do all of the above and additionally:
- Comment on non-friend profiles
- Comment in groups
- Like/Dislike sharedfiles

I hope that helps you!

**Comment by HerrEurobeat** [comment]
You can read more about limited and unlimited accounts here: https://help.steampowered.com/en/faqs/view/71D3-35C2-AD96-AA3A

**Comment by LunaDiscordd** [comment]
ok thanks
