### ISSUE TITLE
???????

### ISSUE THREAD

**Issue by xyzzv** [HerrEurobeat/steam-comment-service-bot#20]
SyntaxError: C:\Users\Win10User\Desktop\zarabianie\steam-comment-service-bot\config.json: Unexpected number in JSON at position 595
    at JSON.parse (<anonymous>)
[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:961:27)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:790:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:703:12)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:830:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:68:18)[39m
    at Object.<anonymous> (C:\Users\Win10User\Desktop\zarabianie\steam-comment-service-bot\src\controller.js:7:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:936:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:790:32)[39m
PS C:\Users\Win10User\Desktop\zarabianie\steam-comment-service-bot>

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.
Could you please send the content of your config.json?
It seems something in it is formatted wrong.

**Comment by xyzzv** [comment]
![obraz](https://user-images.githubusercontent.com/64809237/81175264-89a5b100-8fa3-11ea-8c5a-94a96c77e3c7.png)

**Comment by HerrEurobeat** [comment]
Thanks!
Your config seems to be a bit corrupted. I will investigate further why this might happen.

To fix the error, just delete this part at the bottom of your config:
```
}026610445"
],
    "enableevalcmd": false
```

This should resolve the error for you.

**Comment by xyzzv** [comment]
thanks :0

**Comment by effex1337** [comment]
I had the same issue as well but i fixed it manually.
