### ISSUE TITLE
already logged on?

### ISSUE THREAD

**Issue by effex1337** [HerrEurobeat/steam-comment-service-bot#21]
**Error/Element that doesn't work**
Please include the full error you get or if you get none, describe precisely what happened.
I get this error when trying to log in.
https://cdn.otaku.ooo/gqfad.png

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.
Could it be that you have another instance of the bot already running or that you are logged into the account in your browser?

**Comment by effex1337** [comment]
oh yeah i had it on my desktop then re extracted to downloads folder
and another issue:
https://cdn.otaku.ooo/50x01.png

this happens when i try and use it
the lastcomments.json file is emptied.

**Comment by HerrEurobeat** [comment]
Good to hear that the first error is gone.
Someone else already had that second error but I can't reproduce it. I will push an update asap that should patch the error.

**Comment by effex1337** [comment]
also https://cdn.otaku.ooo/1i5lh.png
these accounts aren't limited

**Comment by HerrEurobeat** [comment]
Sadly probably not something I can fix.
Do the accounts have at least email steam guard enabled?
Is your comment section public?
(Shoudn't be a problem but are you friend with the accounts?)
...and don't forget steam likes to throw random errors. I tried to list all I already experienced here: https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Errors,-FAQ-&-Common-problems

Also, I had this error a few times on my 24/7 hosted bot and sometimes the bot could still comment or just trying again worked. Steam is sadly a bit wierd and has no real documentation so I have to do guess work in many cases.

**Comment by effex1337** [comment]
all the accs have steam guard enabled by email, comments publicly allowed.

also the number of comments look limited by the number of accounts so
suggestion : make it allow commenting again with the same accounts.

**Comment by HerrEurobeat** [comment]
Yep, already a feature I want to include in Version 2.7:
https://github.com/HerrEurobeat/steam-comment-service-bot/projects/2#card-37291634

**Comment by effex1337** [comment]
Ah alrighty will be waiting for it
Maybe next time i get on I'll look at it and maybe make a pr if i succeed.
