### ISSUE TITLE
comment 

### ISSUE THREAD

**Issue by xyzzv** [HerrEurobeat/steam-comment-service-bot#23]
Why as I write !comment 3, I get 1 comment?

**Comment by HerrEurobeat** [comment]
I don't know? You got any errors or anything else? The last time I tried the feature (3-4 days ago) it worked just fine.

And btw, this is more of an question/help needed than an enhancement issue :)

**Comment by xyzzv** [comment]
![obraz](https://user-images.githubusercontent.com/64809237/81300713-4bc68c80-9078-11ea-8f50-9f0d03a39aa2.png)
I don't see any mistakes here

**Comment by HerrEurobeat** [comment]
I neither. How many accounts do you have added to the logininfo.json?
Thats currently the maximum amount of comments you can get. 
This will probably be changed in version 2.7 so that you can comment with one account multiple times.

**Comment by xyzzv** [comment]
I added 3 accounts to the loginingo.json

**Comment by HerrEurobeat** [comment]
So the bot starts up and says 2 child accounts logged in?
And what happens in the chat and console when you type !comment 3?
It's working fine for me and also for other users.

**Comment by xyzzv** [comment]
![obraz](https://user-images.githubusercontent.com/64809237/81313477-335e6e00-9088-11ea-9640-ab72fa16f1f7.png)
![obraz](https://user-images.githubusercontent.com/64809237/81313500-39544f00-9088-11ea-88a7-9d9d9c5bee65.png)
And give me 1comment

**Comment by HerrEurobeat** [comment]
Yes it seems like you have set your mode in config to 1. That means all bots operate by themselves and are not connected with each other. You need to set the mode to 2.
