### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by kura6789** [HerrEurobeat/steam-comment-service-bot#26]
Error: 
![iss](https://user-images.githubusercontent.com/28402838/81852540-796d7300-955b-11ea-99f8-fe9b775e6808.png)
Can u help me?

**Comment by HerrEurobeat** [comment]
Hi, thanks for opening an issue.
I actually made a "fix" already for this bug, it's just not yet out on the master version.
Visit the beta version: https://raw.githubusercontent.com/HerrEurobeat/steam-comment-service-bot/beta-testing/src/bot.js, copy everything, open your `src` folder, delete everything in your `bot.js` file and paste the copied code in there.
This should fix your issue for now.

I hope that I'm getting other bugfixes ready asap so I can push the bugfix update.

**Comment by HerrEurobeat** [comment]
Please start your bot and if the automatic update fixed your problem please close this issue!  

Fixed in commit 29a0d82.
