### ISSUE TITLE
 Unexpected number in JSON at position 590     at parse (<anonymous>)

### ISSUE THREAD

**Issue by HeadShotOfficiale** [HerrEurobeat/steam-comment-service-bot#27]
**Describe the bug**
how to fix it ? , please 
![image](https://user-images.githubusercontent.com/65476729/82164273-7aced080-98b8-11ea-8835-5ab39806cc49.png)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.
It seems like your config.json broke somehow. Could you please send the content of your config.json? That would make it easy for me to fix it for you.

**Comment by HeadShotOfficiale** [comment]
{
    "mode": 2,
    "status": 1,
    "commentdelay": 5000,
    "logindelay": 2500,
    "logcommandusage": true,
    "allowcommentcmdusage": true,
    "skipSteamGuard": false,
    "commentcooldown": 5,
    "globalcommentcooldown": 10000,
    "unfriendtime": 31,
    "playinggames": ["game",440,730],
    "yourgroup": "https://steamcommunity.com/groups/GouKl1",
    "yourgroup64id": "103582791464712227",
    "botsgroupid": "",
    "acceptgroupinvites": true,
    "owner": "https://steamcommunity.com/id/HeadShotOfficiale/",
    "ownerid": ["76561197981411588"],
    "enableevalcmd": false
}981411588"
    ],
    "enableevalcmd": false
}

**Comment by HerrEurobeat** [comment]
Yup, as I already thought.
Remove this:
```
981411588"
],
"enableevalcmd": false
}
```
so your config.json has a `}` at the end. This should fix the error.

**Comment by kblade07** [comment]
@HerrEurobeat 
I also have a problem like this one.
![image](https://user-images.githubusercontent.com/53544168/82266038-6b35a300-991d-11ea-9559-7587a7843738.png)
Before this one appeared, I was inputing steamgaurd code for account 0, at account 1 it says press enter to skip, i typed the guard code and it ways account already logged in, Please restart. But the accounts isnt logged in. How do i fix this?

**Comment by HerrEurobeat** [comment]
Hm, please open a new issue (https://github.com/HerrEurobeat/steam-comment-service-bot/issues/new/choose) that is dedicated to that problem as this one is solved so I would like to close this one.
I will get to you tomorrow asap, but it's 00:42 o' clock in the morning here in Germany and I gotta get some sleep ^^

Thanks!
