### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by effex1337** [HerrEurobeat/steam-comment-service-bot#29]
I got some coins I'd like to donate got a btc address?

**Comment by HerrEurobeat** [comment]
Oh that would be cool! ^^
I don't have a BTC address (yet) but I could create one if it's not too difficult to withdraw money from it etc. 
Otherwise a direct PayPal link is linked in the Sponsor button at the top of the repository.

**Comment by effex1337** [comment]
i dont have paypal so ye bitcoin it is and there are loads of exchangers but you'd have to gather some or you can just buy stuff online.

**Comment by HerrEurobeat** [comment]
So I took some time and created a bitcoin address.
I guess this is the address where someone can send btc to:
`18cEFztHAGfRGBEfGQKBJ2huQWpjrgv95A`

...and I can for example go to blockchain.info to see the balance and to withdraw from the address.
Seems quite simple for now ^^

**Comment by effex1337** [comment]
https://blockchain.com/btc/tx/1d9896bcbbc51d2d94d472c49bedb48551bbe8f62cee7bcb921792c04aed4a65
There ya go was bout to donate 10 euro but btc dropped so sent 5 euro.
Gday ❤️

**Comment by effex1337** [comment]
Also i'd like you to prioritize https://github.com/HerrEurobeat/steam-comment-service-bot/projects/2#card-37291595
I just tried making a bot to auto add friends but it sent 1/5 requests

Here's my attempt at making it.
http://github.com/effex1337/mass-add-steam-friends

**Comment by HerrEurobeat** [comment]
First of all thank you for the 5€!
The auto friend card is already at the top of the Higher Priority list so it will be included in the next update. 
Also cool to see that you tried to create a solution for the problem but it will need alot more checks to make sure that the bot doesn't crash and to let users know if the bot account is limited and therefore can't add friends. I will have to see what I'm going to do in these cases.
