### ISSUE TITLE
Bug, bots do not work correctly after comment

### ISSUE THREAD

**Issue by mrranger** [HerrEurobeat/steam-comment-service-bot#3]
Not all bots leave comments when they leave comments the next time errors get out

[Main] Friend message from [U:1:838512512]: !comment
[Main] postUserComment error: Error: HTTP error 429
[Bot 1] postUserComment error: Error: HTTP error 429
[Bot 2] postUserComment error: Error: HTTP error 429
[Bot 3] postUserComment error: Error: HTTP error 429
[Bot 4] postUserComment error: Error: HTTP error 429
[Bot 5] postUserComment error: Error: HTTP error 429
[Bot 6] postUserComment error: Error: HTTP error 429
[Bot 7] postUserComment error: Error: HTTP error 429
[Bot 8] postUserComment error: Error: HTTP error 429

**Comment by HerrEurobeat** [comment]
This is sadly not a bug I can fix.
This is a cooldown applied by Steam on your accounts when you try to comment too often too fast.
Also, check if all accounts are friend with the requesting account if they are limited.

**Comment by mrranger** [comment]
That is, you need to add all accounts to friends?

**Comment by HerrEurobeat** [comment]
If they are Level 0, yes. This is a limitation from steam. To get an account out of limited mode, you have to at least spend $5 on the steam store.

**Comment by mrranger** [comment]
Well, here's when the bot leaves a comment.
[[Both 2] post User Comment error: error: the settings of this account do not allow adding comments.

**Comment by mrranger** [comment]
[Main] Friend message from [U:1:838225123]: !comment
[Main] Comment: +rep nice Team
[Bot 1] Comment: +rep Best Sniper Ever !
[Bot 2] postUserComment error: Error: The settings on this account do not allow you to add comments.
[Bot 3] postUserComment error: Error: The settings on this account do not allow you to add comments.
[Bot 4] postUserComment error: Error: The settings on this account do not allow you to add comments.
[Bot 5] postUserComment error: Error: The settings on this account do not allow you to add comments.

**Comment by HerrEurobeat** [comment]
Yes, that seems like your accounts Bot 2 to Bot 5 are not allowed to comment on that profile. This is a limitation by Steam on your account, probably because you try to comment with a limited account on a non friend profile. You can read more about this here: https://support.steampowered.com/kb_article.php?ref=3330-IAGK-7663

**Comment by mrranger** [comment]
Everything works, but it happens that the bots comment or not

**Comment by mrranger** [comment]
How to make the user use the bot 1 time in 10 hours

**Comment by HerrEurobeat** [comment]
I am actually working right now on a cooldown feature. If everything is doing well the update could still come today.

**Comment by mrranger** [comment]
Well, thank you very much for the awesome script !!!!!

**Comment by HerrEurobeat** [comment]
:)

Just pushed the update btw, you can read the commit description to see everything that has been added/changed. If there is a new bug or something that I forgot, please open another issue!

**Comment by mrranger** [comment]
Thank you, as soon as I find errors, I will inform you, you are the best!
