### ISSUE TITLE
unexpected  token in json  at position  560

### ISSUE THREAD

**Issue by walterblack21** [HerrEurobeat/steam-comment-service-bot#30]
i did all steps you showed on the video and when i type  node start.js it sais c:\users\fractal\desktop\steam-comment-service-bot-master\config.json: unexpected  token in json  at position  560 
[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1167:22)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:977:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:877:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1019:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (C:\Users\fractal\Desktop\steam-comment-service-bot-master\src\controller.js:7:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:1133:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:977:32)[39m
PS C:\Users\fractal\Desktop\steam-comment-service-bot-master>

**Comment by HerrEurobeat** [comment]
Hi, thanks for opening an issue.
Could you please send the content of your config.json so I can take a look at it? Thanks!

**Comment by walterblack21** [comment]
{
    "version": "2.6",
    "mode": 2,
    "status": 1,
    "commentdelay": 5000,
    "logindelay": 2500,
    "logcommandusage": true,
    "allowcommentcmdusage": false,
    "skipSteamGuard": false,
    "commentcooldown": 5,
    "globalcommentcooldown": 10000,
    "unfriendtime": 31,
    "playinggames": ["!help | 3urobeat", 440, 730],
    "yourgroup": "https://steamcommunity.com/groups/3urobeatGroup",
    "yourgroup64id": "103582791464712227",
    "botsgroupid": "",
    "acceptgroupinvites": true,
    "owner": "https://steamcommunity.com/id/NazigsWalter/,
    "ownerid": ["76561198293063225"],
    "enableevalcmd": false
}

**Comment by HerrEurobeat** [comment]
It seems like you forgot a `"` at the end of your owner link.

Corrected:
```
{
"version": "2.6",
"mode": 2,
"status": 1,
"commentdelay": 5000,
"logindelay": 2500,
"logcommandusage": true,
"allowcommentcmdusage": false,
"skipSteamGuard": false,
"commentcooldown": 5,
"globalcommentcooldown": 10000,
"unfriendtime": 31,
"playinggames": ["!help | 3urobeat", 440, 730],
"yourgroup": "https://steamcommunity.com/groups/3urobeatGroup",
"yourgroup64id": "103582791464712227",
"botsgroupid": "",
"acceptgroupinvites": true,
"owner": "https://steamcommunity.com/id/NazigsWalter/,
"ownerid": ["76561198293063225"],
"enableevalcmd": false
}
```

**Comment by walterblack21** [comment]
tnx this fix it but now it start doing another problem 
TypeError: Cannot read property '0' of undefined
    at Timeout._onTimeout (C:\Users\fractal\Desktop\steam-comment-service-bot-master\src\controller.js:178:41)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
