### ISSUE TITLE
Cannot read property 0

### ISSUE THREAD

**Issue by walterblack21** [HerrEurobeat/steam-comment-service-bot#31]
good morning and i wish you have a nice day i've got new isue and hope you can find the solution =) 

TypeError: Cannot read property '0' of undefined
    at Timeout._onTimeout (C:\Users\fractal\Desktop\steam-comment-service-bot-master\src\controller.js:178:41)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by HerrEurobeat** [comment]
Hi, thanks for opening a dedicated issue for this error.
It seems like you have a syntax error in your logininfo.json.
Please make sure your logininfo.json follows exactly this format:

```
{
	"bot0": ["username0", "password0"],
	"bot1": ["username1", "password1"],
	"bot2": ["username2", "password2"]
}
```

Make sure that after every line is a comma but not on the last line. (like in the example above)
If you want to include more accounts you can just append "bot3": ["name", "pass"] etc.
Also make sure the first line has bot0.
