### ISSUE TITLE
How do I turn off automatic updating?

### ISSUE THREAD

**Issue by mikelobam** [HerrEurobeat/steam-comment-service-bot#32]
I am making some changes, but whenever there is an update, everything I do is going to get tired. How do I turn off the automatic update now?

**Comment by HerrEurobeat** [comment]
Hi thanks for opening an issue.
I already planned to include a feature to disable the automatic updater in the next version. 
The bot won't update automatically anymore but you will still be asked if you would like to update when there is a new version available.
I would really advise against disabling the updater as you won't get any bug/feature updates.

**Comment by mikelobam** [comment]
yes but i don't want it updated I am waiting for the next version.
