### ISSUE TITLE
Download time

### ISSUE THREAD

**Issue by effex1337** [HerrEurobeat/steam-comment-service-bot#36]
Problem:
Cloning this repo take a good amount of time all because of the massive 20 mb gif.

Fix:
Use an external source for the gif.

Have a Good Day!

**Comment by HerrEurobeat** [comment]
Oh well - thanks for saying that! Didn't think about that haha
20mb and it has still complete trash quality and I don't know why since other people managed to get far better quality with a fraction of the size...

**Comment by HerrEurobeat** [comment]
I redid the gif, it now has better quality and is being hosted on my google drive instead on the repo.
