### ISSUE TITLE
I have an idea

### ISSUE THREAD

**Issue by mrranger** [HerrEurobeat/steam-comment-service-bot#4]
I have an idea, how it will not be noticeable that the cheat, you can delay the bots so that they do not write simultaneously

**Comment by HerrEurobeat** [comment]
I'm not 100% sure what you mean but the bots already comment with a delay specified in the config (Default: 5000ms). This proved to be a good delay when I tried to comment with ~5 accounts but it maybe has to be raised when significantly more accounts are being used.

**Comment by mrranger** [comment]
Well, how about a site that a user logs in to a site, and all bots are temporarily added through his account, a person does not participate in this all automatically

**Comment by mrranger** [comment]
Sorry for my English, I use a translator

**Comment by mrranger** [comment]
And if you can, add a function with which you enter the user ID, and you can leave comments for him

**Comment by HerrEurobeat** [comment]
Adding a website is too much work for this project I think. I also don't know if this would work. If you use non limited accounts the user only has to text the main bot, the rest is happening automatically.
You can already comment on a different profile; I added that in the last update. You can read in the Readme.md how it works.

**Comment by mrranger** [comment]
What the hell am I inattentive, I'm sorry what are your plans? what will you add more?

**Comment by mrranger** [comment]
Specifying a profileid is only allowed for the botowner when allowcommentcmdusage is set to false.
If you are the botowner, make sure you added your ownerid to the config.json.

When I try to comment on another profile, it writes to me, but I specified my id

**Comment by HerrEurobeat** [comment]
Current plans are: Include a version checker (if an update is available) and improve console logging & the README.md instructions.

The error basically explains everything. You need to set allowcommentcmdusage to false in the config and specify your profile id in the config.json. If you have done that, it will work. I implemented this to prevent other users commenting on random profiles with your accounts.
