### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by kayrol85** [HerrEurobeat/steam-comment-service-bot#50]
PS D:\steam-comment-service-bot-master> npm install

> protobufjs@6.9.0 postinstall D:\steam-comment-service-bot-master\node_modules\protobufjs
> node scripts/postinstall

npm WARN steam-comment-service-bot@2.0.0 No repository field.

added 152 packages from 192 contributors and audited 152 packages in 7.156s

14 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
PS D:\steam-comment-service-bot-master> npm audit                                                                       
                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Prototype Pollution

  Package         lodash

  Patched in      No patch available

  Dependency of   steamcommunity

  Path            steamcommunity > async > lodash

  More info       https://npmjs.com/advisories/1523

found 1 low severity vulnerability in 152 scanned packages
  1 vulnerability requires manual review. See the full report for details.

HOW DO I FIX?

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue. 
You don't need to run `npm audit` the bot should work just fine. Please just run `node start.js` and see if the bot starts without any errors.

**Comment by HerrEurobeat** [comment]
Since you didn't reply I assume that it is working for you now.
If this problem is still present, feel free to just comment again.
If you encounter another problem/error/bug, please open another issue.
Thanks!
