### ISSUE TITLE
Need unlocked accounts?

### ISSUE THREAD

**Issue by kmko1337** [HerrEurobeat/steam-comment-service-bot#51]
Do i need unlocked accounts ? with 5 euro added on steam

**Comment by HerrEurobeat** [comment]
Hi, you only need unlimited accounts if you want to comment on a non friend profile or use the !addfriend command. Otherwise you can use limited accounts just fine - I'm doing the same thing: https://steamcommunity.com/id/3urobeatscommentbot

**Comment by kmko1337** [comment]
I mean for the bots for comments

Il Sab 4 Lug 2020, 17:32 3urobeat <notifications@github.com> ha scritto:

**Comment by HerrEurobeat** [comment]
You mean the bot accounts that will be posting comments, right? If yes then thats what I meant too.

**Comment by kmko1337** [comment]
Ok, thanks

Il Sab 4 Lug 2020, 17:49 3urobeat <notifications@github.com> ha scritto:

**Comment by HerrEurobeat** [comment]
If this question still persists just reopen the issue again. If you have another question just open another issue.
