### ISSUE TITLE
Id of owner

### ISSUE THREAD

**Issue by sergiubaba** [HerrEurobeat/steam-comment-service-bot#53]
**Error/Element that doesn't work**
Please include the full error you get or if you get none, describe precisely what happened.

**Additional information**
Please add any other information here if you have some.
 hi i have another error when i put my id on ownerid i get this error

       if ((matches = input.match(/^STEAM_([0-5]):([0-1]):([0-9]+)$/))) {
                             ^

TypeError: input.match is not a function
    at new SteamID (C:\Users\sergi\Desktop\steam-comment-service-bot-master\node_modules\steamid\index.js:72:23)
    at C:\Users\sergi\Desktop\steam-comment-service-bot-master\src\controller.js:375:29
    at Array.forEach (<anonymous>)
    at Timeout.<anonymous> (C:\Users\sergi\Desktop\steam-comment-service-bot-master\src\controller.js:374:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.
Could you please send your config.json? I think something with your syntax might be wrong.
Thanks!

**Comment by sergiubaba** [comment]
> Hey, thanks for opening an issue.
> Could you please send your config.json? I think something with your syntax might be wrong.
> Thanks!

{
    "disableautoupdate": false,
    "childaccsplaygames": false,
    "commentdelay": 5000,
    "logindelay": 2500,
    "allowcommentcmdusage": true,
    "skipSteamGuard": false,
    "commentcooldown": 5,
    "globalcommentcooldown": 10000,
    "repeatedComments": 2,
    "unfriendtime": 31,
    "playinggames": ["!help | 3urobeat",440,730],
    "yourgroup": "https://steamcommunity.com/groups/costicacostel12345",
    "botsgroup": "https://steamcommunity.com/groups/costicacostel12345",
    "acceptgroupinvites": true,
    "owner": "https://steamcommunity.com/id/legen1337/",
    "ownerid": [76561198871254506],
    "enableevalcmd": false
}

**Comment by HerrEurobeat** [comment]
Yep you have to put brackets " around your steam id.

**Comment by sergiubaba** [comment]
thanks
