### ISSUE TITLE
Hosting on Heroku, but cannot put the 2FA code anywhere

### ISSUE THREAD

**Issue by Praxand** [HerrEurobeat/steam-comment-service-bot#59]
**Error/Element that doesn't work**
Oops, an error occurred! Details:
[Main] postUserComment error: Error: To post this comment, your account must have Steam Guard enabled.
Please try again in a moment!

**Additional information**
After I turned 2FA on i get an e-mail with the following: Login from new computer. I cannot fill out the code anywhere is there a code to put the shared_secret of the accounts i want to use?

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.
If there is no accessible terminal window on Heroku to put the steam guard code then thats unfortunate. I haven't worked with Heroku yet so I don't know if there is a "solution" to this problem or whatever.

There is a feature planned for the next version (2.9) to include a shared_secret in the logininfo to skip the Steam Guard input but I still have to figure out how I can implement that feature with the library I'm using (node-steam-user and node-steamcommunity).
I'm not sure when this update will come and I have just started working on it, so it will probably take some time.

I'm sorry that the bot might not work with Heroku right now but I haven't thought that there may be a service where you are unable to access the console.

**Comment by HerrEurobeat** [comment]
Since you didn't reply I hope my reply answered your question. If not feel free to just reopen the issue.
If you have other questions/issues please open another issue. Thanks!
