### ISSUE TITLE
Reference Error: x

### ISSUE THREAD

**Issue by qpeckin** [HerrEurobeat/steam-comment-service-bot#69]
**Describe the bug**
Stop the loading process after the last account login.

**Full error**
C:\Users\user\OneDrive\Desktop\comments\src\controller.js:438
                if (module.exports.accisloggedin == true && i == Object.keys(botobject).length + skippednow.length || module.exports.accisloggedin == true && skippednow.includes(i - 1)) { //i is being counted from 0, length from 1 -> checks if last iteration is as long as botobject
                                                                                                 ^

ReferenceError: skippednow is not defined
    at Timeout._onTimeout (C:\Users\user\OneDrive\Desktop\comments\src\controller.js:438:98)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Additional context**
Good luck :)

**Comment by HerrEurobeat** [comment]
Resulting from Discord DMs:
Either removing line 688 `delete skippednow` or reinstalling the bot "fixed" it. I don't know why but it seems to be working now, so hurray!
