### ISSUE TITLE
dnt working

### ISSUE THREAD

**Issue by BABoom12** [HerrEurobeat/steam-comment-service-bot#7]
when i put node start.js i get an error pls help : 
SyntaxError: C:\Users\Acer\Desktop\steam-comment-service-bot-master\steam-comment-service-bot-master\logininfo.json: Unexpected token } in JSON at position 58
    at JSON.parse (<anonymous>)
[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:961:27)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:790:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:703:12)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:830:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:68:18)[39m
    at Object.<anonymous> (C:\Users\Acer\Desktop\steam-comment-service-bot-master\steam-comment-service-bot-master\start.js:6:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:936:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:790:32)[39m

![image](https://user-images.githubusercontent.com/28574138/75109769-62d80f80-562f-11ea-9c93-159e058eef0a.png)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.
Did you check that your logininfo,json has the right format, like in the example?
If you can, please send in your logininfo.json but make sure to remove usernames and passwords or check that your logininfo.json is 100% like this example:
{
	"bot1": ["username1", "password1"],
	"bot2": ["username2", "password2"],
	"bot3": ["username3", "password3"],
        "bot4": ["username4", "password4"]
}
and so on...
Make sure that after every line is a comma but not in the last line.

**Comment by BABoom12** [comment]
Thx

dum., 23 feb. 2020, 11:47 3urobeat <notifications@github.com> a scris:
