### ISSUE TITLE
changing sent message

### ISSUE THREAD

**Issue by notevenftw** [HerrEurobeat/steam-comment-service-bot#70]
hi, is there a way to edit the message sent when someone adds the bot?

thankyou!

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!
At the moment you can only do this by going into the code and changing the line there. The message you are searching for is in line 423 in the `bot.js` file that is in the `src` folder. (`\n` in the message represents a line break)  
  
Although keep in mind that if I should publish an update that this will get reset. I do have a language file on the feature list but I'm not sure when I'll work on this project again as it is pretty much feature complete and has only 1 or 2 bugs that I know of atm.

**Comment by notevenftw** [comment]
thankyou so much! and is there a way to change the !commands? to other words? for instance

!comment to something else?

**Comment by notevenftw** [comment]
thankyou so much!
