### ISSUE TITLE
using the /me option

### ISSUE THREAD

**Issue by Stiefel1234eu** [HerrEurobeat/steam-comment-service-bot#72]
I think it would be a good idea to implement the
"/me" steam chat function to all the bot messages, so "/me" before of the message ;)

![me function](https://user-images.githubusercontent.com/63855548/105384069-1798f900-5c12-11eb-95a3-4e191f73a7ac.png)

Cheers

**Comment by HerrEurobeat** [comment]
Hey, thats a good idea. I have already tried making some changes to the messages but wasn't too sure about it and just didn't do it.  
I'm going to add it to my list and experiment a bit with it the next time I work on this project again.  
  
Thanks for the suggestion!

**Comment by HerrEurobeat** [comment]
I added `/me` to a few messages since I think it doesn't fit to most of the longer messages. I think it fits the shorter messages quite well but many of the longer commands would get nearly unreadable. I hope this is okay.

**Comment by HerrEurobeat** [comment]
Added in master commit 3547d8d (Version 2.10).
