### ISSUE TITLE
Error while trying to log in bot0: Error: InvalidPassword

### ISSUE THREAD

**Issue by Mape921** [HerrEurobeat/steam-comment-service-bot#73]
Every time I run the program this happens:
![Console](https://user-images.githubusercontent.com/77799582/105386001-cd3f5a00-5bc8-11eb-8550-318d26d675fe.PNG)
Here is my logininfo:
![logininfo](https://user-images.githubusercontent.com/77799582/105386095-d9c3b280-5bc8-11eb-9947-7f3e7df8b467.PNG)

Am I doing something wrong?

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
Yes, you need to provide the passwords for the accounts/usernames you provided. Otherwise the bot can't log into those accounts to use them to comment with them.

**Comment by Mape921** [comment]
I put the password. I still get the same error.
![Example](https://user-images.githubusercontent.com/77799582/105413618-3932ba00-5beb-11eb-8318-51011f0453a4.PNG)

**Comment by HerrEurobeat** [comment]
Did you create these accounts on Steam? Do they exist?

**Comment by Mape921** [comment]
ty this worked!
