### ISSUE TITLE
[Help] Steam status

### ISSUE THREAD

**Issue by PanSmuggler** [HerrEurobeat/steam-comment-service-bot#75]
Hi, can you add custom status to all bots or can I know how to do that?
Thanks in advance.

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
At the moment it is only possible to let the child accounts play the Steam games specified in the config or just appear as online.  
I will take note of the idea to also let the child accounts have a custom status!

**Comment by PanSmuggler** [comment]
> Hey, thanks for opening an issue!
> At the moment it is only possible to let the child accounts play the Steam games specified in the config or just appear as online.
> I will take note of the idea to also let the child accounts have a custom status!

Thanks for reply.

**Comment by HerrEurobeat** [comment]
I added a new config setting `childaccplayinggames` which will allow to set games and a custom status for all child accounts just like for the main account. I therefore removed the `childaccsplaygames` setting in the config as this isn't needed anymore.  

Thanks for the idea, this is a great enhancement! :)  
These changes will be available in the beta-testing branch `BETA 2.10 b4` push and the master branch 2.10 push.

**Comment by HerrEurobeat** [comment]
Added in master commit 3547d8d (Version 2.10).
