### ISSUE TITLE
HELP ME STEAM COMMENTS

### ISSUE THREAD

**Issue by vascodavincii** [HerrEurobeat/steam-comment-service-bot#77]
![image](https://user-images.githubusercontent.com/78301580/110240216-d4a6a100-7f85-11eb-89bc-cf6e084e15c1.png)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
It seems like you openend your Power Shell in the wrong folder.  
Please make sure that you open the Power Shell in the folder where all the other files are and run `npm install` again.

**Comment by HerrEurobeat** [comment]
Since you didn't answer I hope you solved that problem so I'm closing this issue. If not, feel free to reopen this issue!
