### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by DJMarkus1337** [HerrEurobeat/steam-comment-service-bot#78]
![image](https://user-images.githubusercontent.com/80347162/110500912-f6c13000-80f9-11eb-8c19-580d006ed616.png)

**Comment by DJMarkus1337** [comment]
(node:5184) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5184) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit

**Comment by DJMarkus1337** [comment]
nice update

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
I got that error two times too but ignored it for now as everything seems to work fine and thought that something else on my machine might have caused that. But I will definitely look into what might cause this error.  

And thanks! :D

**Comment by DJMarkus1337** [comment]
ok worked me im change folder src laset version to new version and off auto update

**Comment by DJMarkus1337** [comment]
folder src fixed

**Comment by DJMarkus1337** [comment]
https://github.com/HerrEurobeat/steam-comment-service-bot/commit/bfa87aec44811c62608f2b31f17a1e83062578bb

**Comment by HerrEurobeat** [comment]
That just caused an error when trying to update because the updater couldn't check for active comment processes but has nothing to do with this issue

**Comment by HerrEurobeat** [comment]
I'll leave this open until I have an idea what caused the error

**Comment by HerrEurobeat** [comment]
I'm not 100% sure this fixed this issue but I'm very certain this should be fine. If this message should appear again anyone can feel free to reopen this issue or create a new one!
