### ISSUE TITLE
change bot message for limited bot accounts

### ISSUE THREAD

**Issue by Stiefel1234eu** [HerrEurobeat/steam-comment-service-bot#84]
I think it would be a good idea to change the way the bot sends you the list of limited bot accounts.
because currently u cannot click the link
![image](https://user-images.githubusercontent.com/63855548/111050921-c35f0800-844f-11eb-9224-04a1bbde6ed1.png)

just add a space between ' and the link:
![image](https://user-images.githubusercontent.com/63855548/111050939-deca1300-844f-11eb-93c6-17984416677e.png)

Cheers

**Comment by HerrEurobeat** [comment]
Yeah I'm not sure anymore why I did it like this but I experimented a bit with it.  
If I recall correctly it had something to do with the link getting replaced by a kind of embed showing the account.  

I will try it out again and find a solution so thanks for opening this issue :)

**Comment by HerrEurobeat** [comment]
You are right, it works perfectly like in your screenshot. Thanks for the suggestion!

**Comment by Stiefel1234eu** [comment]
u're welcome

**Comment by HerrEurobeat** [comment]
Added in 9aaea39 (Version 2.10.2).
