### ISSUE TITLE
comment counter

### ISSUE THREAD

**Issue by Stiefel1234eu** [HerrEurobeat/steam-comment-service-bot#87]
If you are bored and don't know which features to implement next..
Think about a comment counter which:

- maybe is displayed by the !info command
- or a admin only command: that you can check the total comments since the last restart

Cheers!

**Comment by HerrEurobeat** [comment]
Good idea! Thanks for the idea :)

**Comment by HerrEurobeat** [comment]
I made a mix of both of your ideas.  
The bot counts all successful comments and displays them in the `!info` command. This value gets reset after each restart.  
I think this is a good implementation so thanks for the idea :)

**Comment by HerrEurobeat** [comment]
Added in 9aaea39 (Version 2.10.2).
