### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hajimaa** [HerrEurobeat/steam-comment-service-bot#88]
**Describe the bug**
i don't understand which means shared_secret and what shall i do

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.
![image](https://user-images.githubusercontent.com/35498538/111530200-997e4c00-8795-11eb-885c-128a2570b9ee.png)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
You need to put in the username and password of the account you want to use for the bot inside the brackets.  
You don't need a shared_secret, I don't even use one myself. Just leave that there or make the brackets empty.  

This error appeared in the console because it couldn't log in because of a wrong username or password.

**Comment by hajimaa** [comment]
may I take an example from you

**Comment by HerrEurobeat** [comment]
Well this is already the example/template and you just need to fill it in.  

Basically: You create a Steam Account (with Email Steam Guard!) that you want to use for the bot. You then put the username and password of the account inside the brackets in the logininfo.

```
{
   bot0: ["username", "password", ""]
}
```

**Comment by hajimaa** [comment]
Oops, an error occurred!Please wait a moment and try again!Details: [Main] postUserComment error: Error: The settings on this account do not allow you to add comments.Last successful comment: 2021-03-18 12:57:13 (GMT time)

how about this, I already set on privacy settings that anyone can comment

**Comment by HerrEurobeat** [comment]
Are you friend with the bot account? Does the bot account have E-Mail Steam Guard?

**Comment by hajimaa** [comment]
yes i friended with the bot and the bot it does have email steam guard,
i tried again and this happened

[Main] postUserComment error: Error: HTTP error 500

**Comment by HerrEurobeat** [comment]
500 is an error on Steam's side. Then it seems like Steam currently has a problem.  

Here is a list of common problems with descriptions of what they mean:  
https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Errors,-FAQ-&-Common-problems

**Comment by hajimaa** [comment]
alright... it works thanks

**Comment by HerrEurobeat** [comment]
No problem :)  
Great to hear that it works
