### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by meggatrony** [HerrEurobeat/steam-comment-service-bot#9]
Could you explain how your code works in a video on Youtube?

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.

This is a steam comment bot cluster. It allows the user to add as many accounts as he or she wishes and control all of them with one main account. If someone sends the main bot the message !comment, all added accounts will comment on the profile of that person. Besides this, my program also features a bunch of options to customize the behaviour to your liking.

I already planned to make a video on how to set it up but haven't found the time and motivation to do it. Although if you mean to explain the code and how I managed to do what, I probably won't do that as it would take too much time and so on.

**Comment by mrranger** [comment]
Hi, I can shoot a video on tuning, but I won’t say anything, because I don’t know English

**Comment by HerrEurobeat** [comment]
Hi, feel free to create a video if you can show/explain what you are doing with subtitles or what ever. 
Any help is appreciated :)

I will probably create a video myself too in the near future, but feel free to create one!

**Comment by HerrEurobeat** [comment]
As no one answered, I'm closing this one. If you feel the question is not answered enough, just reply again.
