### ISSUE TITLE
Command to let user change quote selection

### ISSUE THREAD

**Issue by David8985** [HerrEurobeat/steam-comment-service-bot#90]
beispiel: 
!changetext [EMOJI/TEXT/OWO]
!defaulttext [quotes.txt]

**Comment by HerrEurobeat** [comment]
Hey, thanks for the suggestion!
At the moment it is only possible for a botowner to specify a custom quote selection as documented [here](https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Commands-documentation). I will think about making this accessible to the user but probably won't enable this to avoid users being able to use your accounts to comment inappropiate stuff on their profiles and therefore putting your account (and reputation) in danger.
