### ISSUE TITLE
error undefuned (Error: connect ECONNREFUSED 127.0.0.1:80)

### ISSUE THREAD

**Issue by noname20214** [HerrEurobeat/steam-comment-service-bot#98]
after restart some times now i have that error, i need to restart something?

[2021-05-20 03:04:03] Logging in... Estimated wait time: 1.95 minutes.
[2021-05-20 03:04:13] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot1. Retrying in 5 seconds...

Couldn't log in bot1 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
Is your proxy 2 offline or blocked by Steam?
Failed account is not bot0. Skipping account...
[2021-05-20 03:04:27] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot3. Retrying in 5 seconds...

Couldn't log in bot3 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
Is your proxy 2 offline or blocked by Steam?
Failed account is not bot0. Skipping account...
[2021-05-20 03:04:40] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot5. Retrying in 5 seconds...

Couldn't log in bot5 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
Is your proxy 2 offline or blocked by Steam?
Failed account is not bot0. Skipping account...
[2021-05-20 03:04:53] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot7. Retrying in 5 seconds...

Couldn't log in bot7 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
Is your proxy 2 offline or blocked by Steam?
Failed account is not bot0. Skipping account...
[2021-05-20 03:05:06] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot9. Retrying in 5 seconds...

Couldn't log in bot9 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
Is your proxy 2 offline or blocked by Steam?
Failed account is not bot0. Skipping account...
[2021-05-20 03:05:17] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot11. Retrying in 5 seconds...

Couldn't log in bot11 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
Is your proxy 2 offline or blocked by Steam?
Failed account is not bot0. Skipping account...
[2021-05-20 03:05:31] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot13. Retrying in 5 seconds...

Couldn't log in bot13 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
Is your proxy 2 offline or blocked by Steam?
Failed account is not bot0. Skipping account...
[2021-05-20 03:05:44] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot15. Retrying in 5 seconds...

Couldn't log in bot15 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
Is your proxy 2 offline or blocked by Steam?
Failed account is not bot0. Skipping account...

**Comment by noname20214** [comment]
> after restart some times now i have that error, i need to restart something?
> 
> [2021-05-20 03:04:03] Logging in... Estimated wait time: 1.95 minutes.
> [2021-05-20 03:04:13] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot1. Retrying in 5 seconds...
> 
> Couldn't log in bot1 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
> Is your proxy 2 offline or blocked by Steam?
> Failed account is not bot0. Skipping account...
> [2021-05-20 03:04:27] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot3. Retrying in 5 seconds...
> 
> Couldn't log in bot3 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
> Is your proxy 2 offline or blocked by Steam?
> Failed account is not bot0. Skipping account...
> [2021-05-20 03:04:40] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot5. Retrying in 5 seconds...
> 
> Couldn't log in bot5 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
> Is your proxy 2 offline or blocked by Steam?
> Failed account is not bot0. Skipping account...
> [2021-05-20 03:04:53] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot7. Retrying in 5 seconds...
> 
> Couldn't log in bot7 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
> Is your proxy 2 offline or blocked by Steam?
> Failed account is not bot0. Skipping account...
> [2021-05-20 03:05:06] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot9. Retrying in 5 seconds...
> 
> Couldn't log in bot9 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
> Is your proxy 2 offline or blocked by Steam?
> Failed account is not bot0. Skipping account...
> [2021-05-20 03:05:17] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot11. Retrying in 5 seconds...
> 
> Couldn't log in bot11 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
> Is your proxy 2 offline or blocked by Steam?
> Failed account is not bot0. Skipping account...
> [2021-05-20 03:05:31] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot13. Retrying in 5 seconds...
> 
> Couldn't log in bot13 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
> Is your proxy 2 offline or blocked by Steam?
> Failed account is not bot0. Skipping account...
> [2021-05-20 03:05:44] Error: connect ECONNREFUSED 127.0.0.1:80 (undefined) while trying to log in bot15. Retrying in 5 seconds...
> 
> Couldn't log in bot15 after 2 attempt(s). Error: connect ECONNREFUSED 127.0.0.1:80 (undefined)
> Is your proxy 2 offline or blocked by Steam?
> Failed account is not bot0. Skipping account...

SOLVED! just reinstalling the bot and moving my login, config and quotes

**Comment by HerrEurobeat** [comment]
Hm okay interesting, good to hear it fixed itself. Haven't seen that error yet.
